/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollectWordsSwitch: typeof import('./src/components/collect-words-switch.vue')['default']
    ReviewPageVocabulary: typeof import('./src/components/review-page-vocabulary.vue')['default']
    SubtitleMaskerSwitch: typeof import('./src/components/subtitle-masker-switch.vue')['default']
  }
}
